name: Publish

on:
  create:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Adding metadata
      run: REF='${{ github.ref }}';echo "VERSION='$(echo $REF | sed 's#^refs/tags/##')'" > ./pytextforge/src/metadata.py

    - name: Install pip dependencies
      run: python -m pip install setuptools wheel twine
    
    - name: Create package
      run: cd ./pytextforge && python setup.py sdist bdist_wheel

    - name: Install package locally
      run: python -m pip install ./pytextforge/dist/pytextforge-*-py3-none-any.whl

    - name: Create output for UT
      run: cd ut && python -m pytextforge --template template.temp --output output.txt --data simpledata=CONTENT_FROM_DATA --json 'js={"content":"CONTENT_FROM_JSON"}' --data-file fromfile=content.txt --json-file fromjsonfile=test.json --data overwrite1=OVER1 --data overwrite1= --data overwrite2=THIS_SHOULD_NOT_BE_THERE --data overwrite2=OVER2;

    - name: Executing UT
      run: cd ut && python ./unit_test.py 

    - name: Push package
      run: cd ./pytextforge && twine upload dist/* -u __token__ -p "${{ secrets.PYPI }}"