name: Publish

on:
  create:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Adding metadata
      run: echo 'VERSION=${{ github.ref }}' > ./pytextforge/src/metadata.py

    - name: Install pip dependencies
      run: python -m pip install setuptools wheel twine
    
    - name: Create package
      run: cd pytextforge && python setup.py sdist bdist_wheel  

    - name: Push package
      run: cd pytextforge && twine upload dist/* -u __token__ -p "${{ secrets.PYPI }}"